### PR TITLE
Use falafel instead of acorn directly, allow custom acorn parser and options to be passed to it

### PR DESCRIPTION
**Pull request by mwolson**
Use falafel instead of acorn directly, allow custom acorn parser and options to be passed to it

- The 'walk' library was inflexible about using custom parsers, since it hardcoded the types of nodes that it expects to see, which did not play well with acorn-jsx.  Using falafel was a workable alternative; it also has easier semantics for updating nodes, so it's no longer necessary to track file offset

- Pass options to falafel, bringing in lodash.assign to make it easier to have default options

- Accept either transform(src, cb) or transform(src, options, cb), moving the ignore_trycatch behavior into options.ignoreTryCatch

- Write tests to verify that ES6 features are handled when passing in the ecmaVersion option.  No attempt is made to handle ES6 import statements yet.

### CODE REVIEW

**Comment by mwolson** [comment]
Slightly better API would be:

```
transform(src, options, cb)
```

but would require major version bump due to backwards-incompatible change

**Comment by tetsuo** [comment]
Thanks @mwolson 
I wrote this module for https://github.com/tetsuo/rewritify indeed. Falafel seemed to be a bit slow back then.

I'm currently on vacation, I'll look into your changes once I get back.

**Comment by mwolson** [comment]
Pushed an update to the pull request:

- Uses arg0.update() instead of node.update().  While working on a separate fork to deal with other kinds of AST fragments, it turns out that updating node could cause stale contents to be written, if node was part of a chained function call.  Not a concern for require() statements, but more robust.

- Switched to the API I like better, which keeps callback arg last always, uses options object as 2nd arg, moves ignore_trycatch into the options in camelcase form to be consistent with acorn's options.

**Comment by tetsuo** [comment]
Hey again.
@mwolson I'm merging this into master, gonna add some changes and release 2.0.0. thx

**Pull request merged**
